[package]
name = "subtle-repro"
version = "0.1.0"
edition = "2024"

[dependencies]
chacha20 = { version = "0.10.0-rc.2", features = ["rand_core", "rng"] }
crypto-bigint = { version = "0.7.0-rc.10", features = ["rand_core"], default-features = false }
rand_core = "0.10.0-rc-1"
