[package]
name = "subtle-repro"
version = "0.1.0"
edition = "2024"

[dependencies]
crypto-bigint = { version = "0.6.1", features = ["rand_core"] }
rand_chacha = "0.3"
rand_core = "0.6"
subtle = "2.6.1"
